export const StatusCodes = {
  SERVER_ERROR_INTERNAL: 500,
  SUCCESS_OK: 200,
  CLIENT_ERROR_BAD_REQUEST: 400,
  CLIENT_ERROR_FORBIDDEN: 403,
  CLIENT_ERROR_NOT_FOUND: 404,
  CLIENT_ERROR_UNAUTHORIZED: 401,
  ERROR_BAD_REQUEST: 422
}