version: "3.9"

services:
  node_app: 
    container_name: node_app
    build: .
    image: oleinik/node_live_app
    network_mode: "host"
    ports:
      - "3000:3000"
    environment: 
      - DB_NAME=fullstack_chat
      - DB_USER=root
      - DB_PASSWORD=root
      - PG_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fullstack_chat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /node_db_data/var/lib/postgresql/data

volumes: 
  node_db_data: {}